var app = angular.module('showyourtrace.configuration', []);
app.constant('PROJECT_NAME', 'showyourtrace');
app.constant('BASE_PATH', 'https://testherokuy.herokuapp.com/showyourtrace');
app.constant('API_END_POINT', '/api/');
app.constant('API_END_POINT_ADMIN', '/admin/api/');
app.constant('IS_AUTH', '${auth}');
app.constant('LOGIN_URL', '/web/login');
app.constant('LOGIN_METHOD','POST');
app.constant('CHECK_LOGIN_URL', '/api/auth');
app.constant('CHECK_LOGIN_URL_ADMIN', '/admin/api/auth');
app.constant('CHECK_LOGIN_METHOD','GET');
app.constant('LOGOUT_URL','/api/auth');
app.constant('LOGOUT_METHOD',  'DELETE');
app.constant('IMG_STORE_PATH',  'https://testherokuy.herokuapp.com/showyourtrace/filestore/');
app.constant('HOME_PAGE',  'https://testherokuy.herokuapp.com/app/index.html#/allDeals');